
spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop_online
    username: grass
    password: 230407
  flyway:
    baseline-on-migrate: true


    upload.path: /C:/Users/merik/IdeaProjects/OnlineShop/src/main/resources/uploads


server:
  port: 8082


